# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helix_envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'helix_envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14helix_envelope.proto\x12\x12glaciereq.helix.v1\"\xcf\x02\n\rHelixEnvelope\x12\x0f\n\x07pair_id\x18\x01 \x01(\t\x12\x0e\n\x06piston\x18\x02 \x01(\t\x12\x0e\n\x06spiral\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\r\n\x05ts_ms\x18\x05 \x01(\x03\x12\x15\n\rjson_fallback\x18\x06 \x01(\x0c\x12?\n\x07numbers\x18\x07 \x03(\x0b\x32..glaciereq.helix.v1.HelixEnvelope.NumbersEntry\x12\x39\n\x04tags\x18\x08 \x03(\x0b\x32+.glaciereq.helix.v1.HelixEnvelope.TagsEntry\x1a.\n\x0cNumbersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helix_envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELIXENVELOPE_NUMBERSENTRY']._loaded_options = None
  _globals['_HELIXENVELOPE_NUMBERSENTRY']._serialized_options = b'8\001'
  _globals['_HELIXENVELOPE_TAGSENTRY']._loaded_options = None
  _globals['_HELIXENVELOPE_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_HELIXENVELOPE']._serialized_start=45
  _globals['_HELIXENVELOPE']._serialized_end=380
  _globals['_HELIXENVELOPE_NUMBERSENTRY']._serialized_start=289
  _globals['_HELIXENVELOPE_NUMBERSENTRY']._serialized_end=335
  _globals['_HELIXENVELOPE_TAGSENTRY']._serialized_start=337
  _globals['_HELIXENVELOPE_TAGSENTRY']._serialized_end=380
# @@protoc_insertion_point(module_scope)
